# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Delete Package Versions
          uses: actions/delete-package-versions@v1.0.3
          with:
    # Comma separated string of package version ids to delete.
    #       package-version-ids: # optional
    # Owner of the repo containing the package version to delete. Defaults to the owner of the repo running the action.

    # owner: # optional
    # Repo containing the package version to delete. Defaults to the repo running the action.

    # repo: # optional
    # Name of the package containing the version to delete. Required if dynamically deleting oldest versions.

           package-name: image
    # Number of versions to delete starting with the oldest version. Defaults to 1.

    # num-old-versions-to-delete: # optional, default is 1
    # Token with the necessary scopes to delete package versions. If num-old-versions-to-delete is used the token also needs the read packages scope. Defaults to github.token scoped to the repo running the action. To delete package versions of a package outside the repo the action is running in use a Personal Access Token stored as a secret.

    # token: # optional, default is ${{ github.token }}
